### ISSUE TITLE
require('electron-prebuilt') occurs an error on Electron app packaged for OS X

### ISSUE THREAD

**Issue by yokada** [PhilipHansen/NightmareJS#2]
I'm using nightmarejs with Electron on OS X El Capitan.
I packaged and launched my electron app for OS X darwin using electron-packager, while the app has given an error as following:

```
Uncaught Exception:
Error: Cannot find module 'electron-prebuilt'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/myuser1/hello-electron-darwin-x64/hello-electron.app/Contents/Resources/app/node_modules/nightmare/lib/nightmare.js:12:29)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```

The nightmare.js error above line 12 is here:

```
var default_electron_path = require('electron-prebuilt');
```

Have someone else encountered same error?

Additional details are here:

node: v5.7.0
electron version: v0.37.2
nightmare version: 2.2.0

thanks.

**Comment by yokada** [comment]
Additional details are here:

node: v5.7.0
electron version: v0.37.2
nightmare version: 2.2.0

thanks.
